enum Major {
  AERO = "Aerospace Engineering",
  AREN = "Architectural Engineering",
  BAEN = "Biological and Agricultural Engineering",
  BMEN = "Biomedical Engineering",
  CHEN = "Chemical Engineering",
  CPSC = "Computer Science",
  CPEN = "Computer Engineering",
  CVEN = "Civil Engineering",
  DAEN = "Data Engineering",
  ELEN = "Electrical Engineering",
  ESET = "Electronic Systems Engineering Technology",
  EVEN = "Environmental Engineering",
  IDIS = "Industrial Distribution",
  ISEN = "Industrial and Systems Engineering",
  MEEN = "Mechanical Engineering",
  MMET = "Manufacturing and Mechanical Engineering Technology",
  MSEN = "Materials Science and Engineering",
  MXET = "Multidisciplinary Technology",
  NUEN = "Nuclear Engineering",
  OCEN = "Ocean Engineering",
  PETE = "Petroleum Engineering",
  MISC = "Other",
}

export { Major };
